linters:
  disable:
    - typecheck
    - gosimple
    - deadcode
    - unused
  enable:
    - gocritic
linters-settings:
  gocritic:
    enabled-checks:
      - ruleguard
    settings:
      ruleguard:
        rules: "linter.go"
